Repository Taein5415/Collaborator, pull requests merged in 2025-01, with the labels that each got.

#6 Debug/common
  README.md
Labels: bug

#13 Book/python
  README.md
  book/python/Chapter1.md
  introTaein.md
  intro_psy.md
Labels: documentation

#14 Book/java
  book/python/Chapter1.md
  java_note/chapter1.md
Labels: documentation, enhancement
